# Generated by Django 5.2 on 2025-05-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("ratings", models.PositiveIntegerField()),
                ("duration", models.CharField(max_length=40)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sci-fi", "sci-fi"),
                            ("social", "social"),
                            ("bio", "bio"),
                        ],
                        max_length=50,
                    ),
                ),
                ("photo", models.URLField()),
            ],
        ),
    ]
