# Generated by Django 5.2 on 2025-04-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='gender',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=30, null=True),
        ),
    ]
